//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kirishima16.Applications.AtomEditor2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kirishima16.Applications.AtomEditor2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutBG {
            get {
                object obj = ResourceManager.GetObject("AboutBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ATOMEditorLogo {
            get {
                object obj = ResourceManager.GetObject("ATOMEditorLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap book_close_b {
            get {
                object obj = ResourceManager.GetObject("book_close_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_b {
            get {
                object obj = ResourceManager.GetObject("copy_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut_b {
            get {
                object obj = ResourceManager.GetObject("cut_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_bl_b {
            get {
                object obj = ResourceManager.GetObject("file_bl_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_pen_b {
            get {
                object obj = ResourceManager.GetObject("file_pen_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_text1_b {
            get {
                object obj = ResourceManager.GetObject("file_text1_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fol_cl_y {
            get {
                object obj = ResourceManager.GetObject("fol_cl_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fol_op_y {
            get {
                object obj = ResourceManager.GetObject("fol_op_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fol_text_yb {
            get {
                object obj = ResourceManager.GetObject("fol_text_yb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_add_down {
            get {
                object obj = ResourceManager.GetObject("item_add_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_add_right {
            get {
                object obj = ResourceManager.GetObject("item_add_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_add_up {
            get {
                object obj = ResourceManager.GetObject("item_add_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_del_simple {
            get {
                object obj = ResourceManager.GetObject("item_del_simple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   オフセット情報のバックアップを作成しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgBackingUpOffset {
            get {
                return ResourceManager.GetString("msgBackingUpOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未保存のノードをエクスポートすることはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgCanotExportWithoutSave {
            get {
                return ResourceManager.GetString("msgCanotExportWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのヘッダを確認しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgCheckingFile {
            get {
                return ResourceManager.GetString("msgCheckingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートするBoxの種類が違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgDifferentNameExportedBox {
            get {
                return ResourceManager.GetString("msgDifferentNameExportedBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このBox(Atom)は誤検出です。
        ///このBoxに対応する一時ファイルは生成されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgFakeNode {
            get {
                return ResourceManager.GetString("msgFakeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boxをインポートするとテンポラリファイルが変更されます。
        ///続行しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgInportWarning {
            get {
                return ResourceManager.GetString("msgInportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートするファイルの形式が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgInvalidExportedBox {
            get {
                return ResourceManager.GetString("msgInvalidExportedBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NgenExecWinの起動に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgNgenFailed {
            get {
                return ResourceManager.GetString("msgNgenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このファイルはMP4またはQTファイルではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgNotMp4File {
            get {
                return ResourceManager.GetString("msgNotMp4File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを開いています： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpeningFile {
            get {
                return ResourceManager.GetString("msgOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box(Atom)を開いています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpeningNode {
            get {
                return ResourceManager.GetString("msgOpeningNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイルのオープンに失敗しました。
        ///書き込み可能な場所に設置されているか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpenLogFileFailed {
            get {
                return ResourceManager.GetString("msgOpenLogFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boxが選択されています： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpenNodeCompleted {
            get {
                return ResourceManager.GetString("msgOpenNodeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノードが開けませんでいた。
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpenNodeFailed {
            get {
                return ResourceManager.GetString("msgOpenNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ファイルを開けませんでした。
        ///ほかのアプリケーションで開かれていないか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpenReadFileFailed {
            get {
                return ResourceManager.GetString("msgOpenReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先ファイルを開けませんでした。
        ///ほかのアプリケーションで開かれていないか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgOpenWriteFileFailed {
            get {
                return ResourceManager.GetString("msgOpenWriteFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細情報表示処理で例外が発生しました。
        ///情報が正しく表示されていない可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgParseNodeFailed {
            get {
                return ResourceManager.GetString("msgParseNodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのBox(Atom)を解析しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgParsingFile {
            get {
                return ResourceManager.GetString("msgParsingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box(Atom)を解析しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgParsingNode {
            get {
                return ResourceManager.GetString("msgParsingNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Readmeファイルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgReadmeNotFount {
            get {
                return ResourceManager.GetString("msgReadmeNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先ファイルの削除に失敗しました。
        ///ほかのアプリケーションで開かれていないか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgRemoveFileFailed {
            get {
                return ResourceManager.GetString("msgRemoveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンポラリフォルダの削除に失敗しました。
        ///アプリケーション終了後に以下のフォルダを削除してください。
        ///{0}
        ///----
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgRemoveTmpDirFailed {
            get {
                return ResourceManager.GetString("msgRemoveTmpDirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンポラリファイルを削除しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgRemoveTmpFiles {
            get {
                return ResourceManager.GetString("msgRemoveTmpFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先ファイルを削除しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgRemovingFile {
            get {
                return ResourceManager.GetString("msgRemovingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テンポラリフォルダを削除しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgRemovingTmpDir {
            get {
                return ResourceManager.GetString("msgRemovingTmpDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルのBox(Atom)を表示しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgRenderingNodeToTree {
            get {
                return ResourceManager.GetString("msgRenderingNodeToTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgSaveFileCompleted {
            get {
                return ResourceManager.GetString("msgSaveFileCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを保存しています： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgSavingFile {
            get {
                return ResourceManager.GetString("msgSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先ファイルに書き込んでいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgWritingFile {
            get {
                return ResourceManager.GetString("msgWritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オフセット情報を修正しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgWritingOffset {
            get {
                return ResourceManager.GetString("msgWritingOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box(Atom)の編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeEditNode {
            get {
                return ResourceManager.GetString("opeEditNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boxのエクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeExport {
            get {
                return ResourceManager.GetString("opeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Boxのインポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeImport {
            get {
                return ResourceManager.GetString("opeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最適化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeNgen {
            get {
                return ResourceManager.GetString("opeNgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeOpenFile {
            get {
                return ResourceManager.GetString("opeOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box(Atom)を開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeOpenNode {
            get {
                return ResourceManager.GetString("opeOpenNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string opeSaveFile {
            get {
                return ResourceManager.GetString("opeSaveFile", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap paste_text_b {
            get {
                object obj = ResourceManager.GetObject("paste_text_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap project_bl_b {
            get {
                object obj = ResourceManager.GetObject("project_bl_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {0}は編集されています。
        ///Box(Atom)を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string qesSaveAllNode {
            get {
                return ResourceManager.GetString("qesSaveAllNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のファイルに上書きしてよろしいですか？
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string qesSaveFile {
            get {
                return ResourceManager.GetString("qesSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のBox(Atom)は編集されています。
        ///Boxを保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string qesSaveNode {
            get {
                return ResourceManager.GetString("qesSaveNode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save_b {
            get {
                object obj = ResourceManager.GetObject("save_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveAs_b {
            get {
                object obj = ResourceManager.GetObject("saveAs_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   _ROOT_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sysRootNode {
            get {
                return ResourceManager.GetString("sysRootNode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tab_del_b {
            get {
                object obj = ResourceManager.GetObject("tab_del_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_many_del_b {
            get {
                object obj = ResourceManager.GetObject("tab_many_del_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_many_save_b {
            get {
                object obj = ResourceManager.GetObject("tab_many_save_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_new_b {
            get {
                object obj = ResourceManager.GetObject("tab_new_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_save_b {
            get {
                object obj = ResourceManager.GetObject("tab_save_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ATOMEditor - {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tplFormText {
            get {
                return ResourceManager.GetString("tplFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AtomEditor - {0}を開いています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tplFormTextLoading {
            get {
                return ResourceManager.GetString("tplFormTextLoading", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap win_iframe {
            get {
                object obj = ResourceManager.GetObject("win_iframe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
